### ISSUE TITLE
Define and document status values

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/meshdb#168]
Define and document what each of the status values means. Some discussion here: https://nycmesh.slack.com/archives/C06GW3Q92TY/p1707029793632389

**Comment by james-otten** [comment]
Every model that has a status value

**Comment by Andrew-Dickinson** [comment]
https://nycmesh.slack.com/archives/C06GW3Q92TY/p1711770919333109?thread_ts=1711769003.400379&cid=C06GW3Q92TY

**Comment by james-otten** [comment]
Template:
https://wiki.mesh.nycmesh.net/books/services-software/page/meshdb-status-values

**Comment by Andrew-Dickinson** [comment]
As I worked through this, I realized we have a problem with potential links not showing on our map and opened #402

I think we should also consider renaming `Planned` on the device and link tables, since `Potential` seems more accurate based on the descriptions I came up with
