### ISSUE TITLE
Investigate Admin Panel tests

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshdb#217]
We need something that will let us test the AdminUI itself. #215 fixes a bug that is difficult (if not impossible) to catch in our current testing setup because it has to do with the templates. There was a problem with one of the templates causing reverse FK fields to be blanked out on the building and member `change` routes.

https://www.selenium.dev/selenium-ide/ might be a decent candidate.

**Comment by Andrew-Dickinson** [comment]
Selenium is powerful but very heavy (bundles chromium). We only need it if we want to run the javascript, which on the admin page doesn't do very much. For just asserting things about the generated HTML responses, using [beautifulsoup](https://beautiful-soup-4.readthedocs.io/en/latest/) should be much easer to do

**Comment by WillNilges** [comment]
we could use datadog for this <3
