### ISSUE TITLE
Create dummy dataset

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshdb#218]
We need a publicly available dataset for people to import/use for testing. We want to invite everyone to work on this project, but some folks haven't quite reached the level of trust needed to be given unfettered access to member details.

Ideally, this would take the form of a set of sql dumps that could exist in `HACKING/sample_data`. Perhaps we could also set up a `.dev` instance that's 100% open (probably nuked nightly) for people to play with.

**Comment by WillNilges** [comment]
#262 allows you to scrub an existing database of all real member data. We still need a "generator" of sorts to fully synthesize data with a single command.

**Comment by Andrew-Dickinson** [comment]
What if we set up the import box to produce an anonymized dataset each day, and upload it somewhere semi-public?

**Comment by Andrew-Dickinson** [comment]
@WillNilges remaining work here is to anonymize the notes fields everywhere (and probably address too?)
