### ISSUE TITLE
Correct/Deduplicate `DeviceType` in the Import Script

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshdb#238]
We need to fix stuff like this:
![image](https://github.com/WillNilges/meshdb/assets/42927786/22af68f7-9cda-441b-a289-99b0b07747d5)

![image](https://github.com/WillNilges/meshdb/assets/42927786/f63ded4a-d255-45a8-8fb2-ab272ca4ad36)

![image](https://github.com/WillNilges/meshdb/assets/42927786/f619ef74-8c1a-4153-8603-491f06abe45d)

**Comment by WillNilges** [comment]
It might be sufficient to just make everything Title Case or something.

**Comment by WillNilges** [comment]
Some of this is coming from UISP unfortunately.

![image](https://github.com/WillNilges/meshdb/assets/42927786/b0e18942-624d-4ca9-b3d3-afc9c07df11b)

**Comment by Andrew-Dickinson** [comment]
Based on where things are going with #383, this may be no longer needed

**Comment by WillNilges** [comment]
I'm unassigning myself from this, since we most likely won't need to do this.

**Comment by Andrew-Dickinson** [comment]
This field has been removed in #457, closing as won't fix
