### ISSUE TITLE
Sectors getting improperly added as Devices

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshdb#239]
Something is wrong with the import script/UISP stuff that is causing some Sectors(?) to show up as Devices.

![image](https://github.com/WillNilges/meshdb/assets/42927786/eb444797-94b4-4836-a19a-3f807543621b)

They’re probably not listed in the spreadsheet, or we couldn’t match the spreadsheet rows with UISP

**Comment by Andrew-Dickinson** [comment]
Asked Olivier about this, seems like they're missing from the spreadsheet

**Comment by Andrew-Dickinson** [comment]
There's an SN1 refresh coming soon, so most of these sectors are likely getting messed with anyway

**Comment by Andrew-Dickinson** [comment]
Added rows to the spreadsheet for the Saratoga devices today, talking to John B about SN1

**Comment by Andrew-Dickinson** [comment]
More problem devices:
- [ ] nycmesh-317-west
- [ ] nycmesh-2090-west
- [ ] nycmesh-3461-northwest
- [ ] nycmesh-3461-north
- [ ] nycmesh-1340-outdoor-east
- [ ] nycmesh-227-ps5ac-northnortheast
- [ ] nycmesh-731-60gx3-north
- [ ] nycmesh-227-ps5ac-north
- [ ] nycmesh-641-south

Wave APs:
- [ ] nycmesh-5916-waveap-west
- [ ] nycmesh-5916-waveap-northeast
- [ ] nycmesh-5916-waveap-south
- [ ] nycmesh-1933-waveap-northeast
- [ ] nycmesh-3461-waveap-north
- [ ] nycmesh-3461-waveap-south
- [ ] nycmesh-227-waveap-north

**Comment by Andrew-Dickinson** [comment]
Added all the new and old SN1 devices to spreadsheet

**Comment by Andrew-Dickinson** [comment]
Added all the missing 5GHz sectors to the spreadsheet

**Comment by Andrew-Dickinson** [comment]
Added #493 to capture the 60 GHz devices as a post-launch follow up
