### ISSUE TITLE
The BIN number box appears really small

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/meshdb#309]
On the Building page, you can't read the whole BIN since it gets cut off, kinda annoying. There's got to be a way to fix this

![Screenshot 2024-04-01 at 01 23 21](https://github.com/nycmeshnet/meshdb/assets/3138937/b4924fad-453a-4587-9257-55270e3f8ab1)

**Comment by owais34** [comment]
Hi Andrew , i would like to work on this.

**Comment by Andrew-Dickinson** [comment]
Great! Let me know if you need any support getting started

**Comment by owais34** [comment]
I've successfully setup the dev environment , can help me recreate this issue ? or help point out the specific page where this occurs.

**Comment by Andrew-Dickinson** [comment]
If you have the admin UI working, you should be able to create a new `Building` object:
http://127.0.0.1:8000/admin/
<img width="825" alt="Screenshot 2024-04-01 at 13 23 16" src="https://github.com/nycmeshnet/meshdb/assets/3138937/6f63aeab-64e6-4cdd-873e-bab1f3268e16">


Just use fake data for testing. BIN numbers are usually 7 digits long, e.g. `1003625`.

Once you create the building, navigate to the "edit" page for it. It should look like my screenshot at the top of this issue, where some digits get cut off

**Comment by Andrew-Dickinson** [comment]
I think this is something that needs to be configured in the `src/meshapi/admin.py` file, to make the text box a bit bigger. There's probably a Django guide online somewhere that says how to adjust it

**Comment by owais34** [comment]
Gotcha boss , I'll fix this.

**Comment by owais34** [comment]
Done boss , https://github.com/nycmeshnet/meshdb/pull/318
![image](https://github.com/nycmeshnet/meshdb/assets/37238759/22da76ea-e8d4-431e-aa4a-0fecf9e65853)
