### ISSUE TITLE
Allow raw SQL queries for analytics access

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/meshdb#312]
Come up with a way to allow raw SQL queries (via a read-only user) for analytics workloads. Export to CSV. Ideally this would be via some type of UI, so that folks don't have to download a postgres client. Maybe there's some kind of Django analytics library that helps with this?

https://nycmesh.slack.com/archives/C06GW3Q92TY/p1712013900917419

**Comment by WillNilges** [comment]
We could use pgadmin for this.

**Comment by WillNilges** [comment]
https://www.pgadmin.org/

**Comment by WillNilges** [comment]
https://hub.docker.com/r/dpage/pgadmin4/

**Comment by james-otten** [comment]
Redshift vs bigquery? Set up a job to automatically import from offsite backups?

**Comment by Andrew-Dickinson** [comment]
Definitely possible but probably overkill for our DB size and low traffic volumes. I don’t think we mind cohabitation of OLAP and OLTP
