### ISSUE TITLE
Improve homepage

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshdb#320]
I find myself fumbling with the links on the homepage (https://db.grandsvc.mesh.nycmesh.net). Wondering if someone could add some buttons like https://forms.grandsvc.mesh.nycmesh.net or something
<img width="1100" alt="image" src="https://github.com/nycmeshnet/meshdb/assets/42927786/3a759d88-8c5a-4bf7-8a8c-c329e1b26e83">

What if we had something like this?

# [Join Our Community Network!](https://forms.grandsvc.mesh.nycmesh.net/join/)

## Member Tools
[Line of Sight Tool](https://los.grandsvc.mesh.nycmesh.net/)
[Map](https://map.grandsvc.mesh.nycmesh.net/)

## Volunteer Tools
[Admin Panel](https://db.grandsvc.mesh.nycmesh.net/admin)
[Other Forms](https://forms.grandsvc.mesh.nycmesh.net/)

## Developer Tools
[MeshDB Data API](https://db.grandsvc.mesh.nycmesh.net/api/v1/)
[API Documentation (Swagger)](https://db.grandsvc.mesh.nycmesh.net/api-docs/swagger/)
[API Documentation (Redoc)](https://db.grandsvc.mesh.nycmesh.net/api-docs/redoc/)

**Comment by evnxprk** [comment]
So what exactly are you looking to add? I can help with this issue but would need more clarification and explanation on what you would need.

**Comment by WillNilges** [comment]
@evnxprk This is another option: 
![image](https://github.com/nycmeshnet/meshdb/assets/42927786/0d0d53e7-1565-490c-bb4a-d05c0ec33e83)

**Comment by WillNilges** [comment]
@evnxprk Are you still interested in working on this?
