### ISSUE TITLE
Panorama Viewer only works for Admins

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshdb#338]
Django seemingly has a hardcoded, undocumented obligation to render data as plaintext when you have view-only permissions.
![image](https://github.com/nycmeshnet/meshdb/assets/42927786/19682b08-ccd5-4d82-a127-62e918fb5f2f)

I need to render the panorama viewer. There may be a workaround.

Further reading:

https://code.djangoproject.com/ticket/30577
https://stackoverflow.com/questions/14832739/django-admin-how-to-display-widget-on-readonly-field

**Comment by WillNilges** [comment]
This is still an issue as of 2 months ago.

https://www.reddit.com/r/django/comments/1al8qlv/admin_readonly_field_with_custom_widgets_are/

**Comment by Andrew-Dickinson** [comment]
> I generally find that when I start fighting with Django admin I'm pushing on a closed door and just write a discrete app instead.

An ominous point that I fear we may be bumping into in more ways than one...
