### ISSUE TITLE
Add canary monitoring

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/meshdb#442]
MVP: just checking for 200 on '"We're Meshin"', but could do a lot more advanced stuff, including querying all the various API endpoints, and even things like checking data integrity (e.g. make sure NN3 is "Brian Hall", make sure the number install requests is increased from the last check, etc.) to make sure we didn't run the scramble script or delete the database :(

**Comment by WillNilges** [comment]
http://alerts.mesh.nycmesh.net:3001/status/meshdb
This covers us for heartbeats. What this ticket describes is live synthetics testing. That would likely be another service of some kind. Datadog could do it, so maybe related to (#88)?

**Comment by Andrew-Dickinson** [comment]
#261 related also
