### ISSUE TITLE
Fall back to pelias when geosearch.planninglabs.nyc isn't available

### ISSUE THREAD

**Issue by james-otten** [nycmeshnet/meshdb#503]
Avoid failure if `geosearch.planninglabs.nyc` isn't available. Instead:

- In nycmeshnet/meshdb#300 , @Andrew-Dickinson suggested that it would be possible to fall back to the pelias container if `geosearch.planninglabs.nyc` isn't available.
- Avoid a 500 if `geosearch.planninglabs.nyc` and/or pelias isn't available.

**Comment by Andrew-Dickinson** [comment]
Closing in favor of https://github.com/nycmeshnet/meshforms/issues/77
