### ISSUE TITLE
[dev3] Use backups to reset the dev environment every ~12h

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshdb#504]
In order to keep the dev DB consistent (and not full of crap), we should restore it from backups with S3 every so often. This has the added benefit of testing our backups :)

**Comment by james-otten** [comment]
It does spreadsheet import daily IIRC

**Comment by WillNilges** [comment]
Good to know. I think we should still set this up because we're gonna kill the spreadsheet.
