### ISSUE TITLE
Don't crash when a user lives in New Jersey

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/meshdb#522]
Currently there is not test coverage for NJ Join Form submissions, so it's a bit of UB. We should make sure that we're covering that case and know exactly what will happen.

**Comment by Andrew-Dickinson** [comment]
Adding to the launch tracker for visibility, though I expect this is controversial. I am willing to move this back to after launch if others feel strongly

**Comment by WillNilges** [comment]
Yeah I don't think this is blocking. I think it's fair (for now) to say, "if you're in NJ, contact us and we'll sort you out."

**Comment by WillNilges** [comment]
We should take New Jersians' info at face value and make an install. Probably drop a message in Slack about it.

We could also log it to S3?

**Comment by Andrew-Dickinson** [comment]
![Uploading Screenshot 2024-10-08 at 15.17.48.png…]()

Current UX for reference
