### ISSUE TITLE
Exclude maintenance mode URLs from API docs

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/meshdb#569]
....or document them

**Comment by WillNilges** [comment]
I am leaning towards leaving them undocumented. They are for internal use only, similar to the update panoramas route. We can talk about them on the wiki, maybe, but they're absolutely not intended for use by anybody except a human or meshdb itself.

**Comment by Andrew-Dickinson** [comment]
Let’s remove the pano ones also then
