### ISSUE TITLE
Saving buildings without panoramas doesn't work

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/meshdb#603]
Seems like only when the `EDIT_PANORAMAS` feature flag is set? I can repro in prod, beta, and local dev on both chrome and firefox. @WillNilges can't repro at all

**Comment by Andrew-Dickinson** [comment]
Possibly fixed by #602?

**Comment by WillNilges** [comment]
I still can't reproduce this in dev on firefox or chrome.

**Comment by Andrew-Dickinson** [comment]
Fixed in #622
