### ISSUE TITLE
MeshDB Query

### ISSUE THREAD

**Issue by OlivierMorf** [nycmeshnet/meshdb#662]
Is that in meshdb or meshforms ?
Would it be possible to add to the query https://forms.nycmesh.net/query filters (radio buttons) to show only the 
- Active
or
- Closed
or
- not installed (empty)
Or a combination.

Most often we want the Active. Occasionally probably the request not yet installed.

**Comment by Andrew-Dickinson** [comment]
Closing this, but tracking the request via: https://github.com/nycmeshnet/meshforms/issues/99
