### ISSUE TITLE
Add basic monitoring

### ISSUE THREAD

**Issue by Andrew-Dickinson** [nycmeshnet/meshdb#88]
We should receive some kind of basic alerts for `5xx` errors in production. Probably a slack message?

**Comment by vivinano** [comment]
I created some middleware and testing it out now possible super basic but seems to do error handling

**Comment by Andrew-Dickinson** [comment]
We should also include monitoring of the "supplemental" services. Admin map, regular map, LOS DB, etc

**Comment by Andrew-Dickinson** [comment]
New requirement: if the celery workers haven't run in a long time we should be alerted
